### ISSUE TITLE
OpenGPG skipping on Forge(NeoForge)

### ISSUE THREAD

**Issue by AdamCalculator** [AdamCalculator/DynamicPack#31]
java.lang.IllegalAccessError: class org.bouncycastle.crypto.CryptoServicesRegistrar (in module org.bouncycastle.provider) cannot access class java.util.logging.Logger (in module java.logging) because module org.bouncycastle.provider does not read module java.logging

```java
Exception in thread "SyncThread0" java.lang.IllegalAccessError: class org.bouncycastle.crypto.CryptoServicesRegistrar (in module org.bouncycastle.provider) cannot access class java.util.logging.Logger (in module java.logging) because module org.bouncycastle.provider does not read module java.logging
	at TRANSFORMER/org.bouncycastle.provider/org.bouncycastle.crypto.CryptoServicesRegistrar.<clinit>(CryptoServicesRegistrar.java:28)
	at TRANSFORMER/org.bouncycastle.provider/org.bouncycastle.crypto.digests.SHA1Digest.<init>(Unknown Source)
	at TRANSFORMER/org.bouncycastle.provider/org.bouncycastle.crypto.digests.SHA1Digest.<init>(Unknown Source)
	at TRANSFORMER/org.bouncycastle.pg/org.bouncycastle.openpgp.operator.bc.BcKeyFingerprintCalculator.calculateFingerprint(Unknown Source)
	at TRANSFORMER/org.bouncycastle.pg/org.bouncycastle.openpgp.PGPPublicKey.init(Unknown Source)
	at TRANSFORMER/org.bouncycastle.pg/org.bouncycastle.openpgp.PGPPublicKey.<init>(Unknown Source)
	at TRANSFORMER/org.bouncycastle.pg/org.bouncycastle.openpgp.PGPPublicKeyRing.<init>(Unknown Source)
	at TRANSFORMER/org.bouncycastle.pg/org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at TRANSFORMER/org.bouncycastle.pg/org.bouncycastle.openpgp.PGPPublicKeyRingCollection.<init>(Unknown Source)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.util.enc.GPGSignatureVerifier.readPublicKey(GPGSignatureVerifier.java:88)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.util.enc.GPGSignatureVerifier.verify(GPGSignatureVerifier.java:72)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.util.Urls.parseContentAndVerify(Urls.java:47)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.pack.DynamicRepoRemote.sync0(DynamicRepoRemote.java:139)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.pack.DynamicRepoRemote.lambda$sync$0(DynamicRepoRemote.java:114)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.PackUtil.openPackFileSystem(PackUtil.java:58)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.pack.DynamicRepoRemote.sync(DynamicRepoRemote.java:112)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.pack.Pack.sync0(Pack.java:144)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.pack.Pack.sync(Pack.java:110)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.sync.SyncingTask.run(SyncingTask.java:43)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.sync.SyncThread.startSync(SyncThread.java:41)
	at TRANSFORMER/dynamicpack@1.0.15.1/com.adamcalculator.dynamicpack.sync.SyncThread.run(SyncThread.java:25)
```

Issues about this on bc: https://github.com/bcgit/bc-java/issues/1608

**Comment by AdamCalculator** [comment]
Maybe I don't understand gradle...

**Comment by AdamCalculator** [comment]
Temp skip located here: https://github.com/AdamCalculator/DynamicPack/blob/f37db08378305918205315c9cf61e21247c2b651/common/src/main/java/com/adamcalculator/dynamicpack/Support.java

**Comment by AdamCalculator** [comment]
OpenPGP support removed.
